config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resources :sessions, only: %i[new create destroy show]
  resources :events
  resources :invitations, only: [:create]

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  match 'signout', to: 'sessions#destroy', via: 'delete'
  get 'invite', to: 'invitations#new'
  
  match "signup", to: "users#new", via: "get"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'

  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  scope :upcoming, -> { where('date >= ?', DateTime.now.to_date) }
  scope :past, -> { where('date < ?', DateTime.now) }

  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances, foreign_key: :attendee_id

  validates :title, presence: true, length: { minimum: 10, maximum: 40 }
  validates :location, presence: true
  validates :description, presence: true, length: { minimum: 30, maximum: 250 }
  validates :date, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :attendances, foreign_key: 'user_id'
  has_many :attended_events, through: :attendances
  has_many :invitations, foreign_key: 'invitee'
  has_many :invited_events, through: :invitations

  validates :name, presence: true, length: { minimum: 10, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 150 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def upcoming_events
    attended_events.upcoming
  end

  def past_events
    attended_events.past
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def index
    @events = Event.all
    @upcoming = Event.upcoming
    @past = Event.past
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.all
    @upcoming = Event.upcoming.order(date: :asc)
    @past = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = 'Your event was created successfully'
      redirect_to @event
    else
      flash[:danger] = 'Event was not created'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :description, :date)
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)

    if !User.find_by(email: @invitation.email).nil?
      @invitation.invited_user_id = User.find_by(email: @invitation.email).id
      @invitation.save
      flash[:notice] = 'Invitation sent'
      redirect_to event_path(params[:invitation][:event_id])
    else
      flash[:warn] = 'There is no user with this email'
      redirect_to invite_path(eventid: params[:invitation][:event_id])
    end
  end

  def show; end

  private

  def invitation_params
    params.require(:invitation).permit(:email, :event_creator, :event_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    redirect_to root_url if signed_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user
      # Log the user in and redirect to the user's show page.
      flash[:success] = 'Thank you for signing in!'
      sign_in @user
      remember @user
      redirect_to user_url(@user[:id])
    else
      # Create an error message.
      flash[:error] = 'Can not verify your email of password'
      render 'new'
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Your account was created successfully'
      redirect_to @user
    else
      flash[:danger] = 'User was not created'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  def index
    @users = User.all.order(id: :asc)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find(user_id)
      if user&.authenticate(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def remember(user)
    cookies.permanent.signed[:user_id] = user.id
  end

  def forget(_user)
    cookies.delete(:user_id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/_attendees.html.erb
<div class="text-center jumbotron">
    <% if @event.invitations.any? %>
        <h3 class="text-success">Attendee: </h3>
        <% @event.invitations.each do |attendee| %>
            <span class="attendee"><%= attendee.invitee.name %>
            </span> <br/>
        <% end %>
    <% else %>
        No attendees
    <% end %><br/>
</div>

app/views/events/_event.html.erb
<li class="media">
  <div class="media-left">
    <!--<a href="#"><%#= link_to gravatar_for(event.user_id, size: 30), event.user_id %></a> %> -->
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to event.title, event_path(event) %></h4>
      <p>
        Location:
        <%= event.location %><br>
        Date: 
        <%= event.date %>
      </p>
      <p>
      	Published On: <%= event.created_at.strftime('%b %d, %Y') %><br>
        <% if signed_in? %>
      	By: me<br>
        <% else %>
        By: <%= event.user_id.username %><br>
        <% end %>
        
      </p>
      
  </div>
</li>

app/views/events/_event_details.html.erb
    <% if @upcoming.any? %>
        <ul>
            <% @upcoming.each do |event| %>
            <div class="breadcrumb">
                <h3><%= event.title %></h3>
                Location: <%= event.location %><br>
                Date: <%= event.date.to_date %><br>
                Description: <%= event.description %>
                <small class="createdby" >Created by: <%= event.creator.name %></small>
            </div>
                <% end %>
        </ul>
    <% else %>
        <h4 class="breadcrumb">No upcoming events</h4>    
    <% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <%= render 'shared/error_messages_for_event'%>

    <%= f.label :date %>
    <%= f.text_field :date, :class => "form-control" %>

    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>

    <%= f.label :location %>
    <%= f.text_field :location, :class => "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control" %>

  <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "Create your Events", class: "btn btn-primary form-control mt-2" %>

<% end %>

app/views/events/_list_all_events.html.erb
<h2 class="text-center font-weight-bold bg-dark text-white mt-1 rounded">Popular Events</h2>


<% if @events.any? %>

<% @events.each_slice(3) do |event| %>
    <div class="row">
        <% @events.each do |e| %>
            <div class="col-sm-12 col-md-4 center">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <%= image_tag "pp.jpeg", :class => "card-img-top" %>
                        <h5>Title: <%= e.title %></h5>
                        <h6>Location: <%= e.location %></h6>
                        <h6>Date: <%= e.date %></h6>
                    </div>
                </div>
            </div>
        <% end %>
    </div><br> 
<% end %>    
   
<% end %>

app/views/events/_past.html.erb
<h3 class="text-center text-danger">Past Events</h3>
    <% if @past.any? %>
            <% @past.each do |event| %>
            <div class="breadcrumb">
            <ul class="event-list">
                <li><h3><%= event.title %></h3></li>
                <li>Location: <%= event.location %></li>
                <li>Date: <%= event.date.to_date %></li>
                <li>Description: <%= event.description %></li>
                <li><small class="createdby">Created by: <%= event.creator.name %></small></li>
            </ul>
            </div>
            <% end %>
    <% else %>
        <h4 class="breadcrumb">No past events</h4>   
    <% end %>

app/views/events/_past_events.html.erb
<div class="text-center jumbotron">
    <h4 class="text-success">Current Events</h4>
    <% if @event.inspect %>
        <%= render @event %>
    <% end %>
</div>

app/views/events/_upcoming.html.erb
<section class="container">

<h3 class="text-center text-success">Upcoming Events</h3>
    <% if @upcoming.any? %>
            <% @upcoming.upcoming.each do |event| %>
            <div class="breadcrumb">
            <ul class="event-list">
                <li><h3><%= event.title %></h3></li>
                <li>Location: <%= event.location %></li>
                <li>Date: <%= event.date.to_date %></li>
                <li>Description: <%= event.description %></li>
                <li><small class="createdby">Created by: <%= event.creator.name %></small></li>
            </ul>
            </div>
            <% end %>
    <% else %>
        <h4 class="breadcrumb">No past events</h4>   
    <% end %>

    </section>

app/views/events/index.html.erb
<div class="row">
    <div class="col-sm-12">
        <%= render 'upcoming' %>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="center mt-10">
                <h2 class="text-center">Create New Event</h2>
                <%= render 'form' %>
            </div>
        </div>   
        <div class="col-md-3"></div>    
    </div>   
</div>

app/views/events/show.html.erb
<div class="row m-0">
  <div class="col-md-6 card p-5 m-5">
      <h1><%= @event.title%></h1>
      <p class="card-subtitle">by <%= @event.creator.name %></p>
      <br>
      <div class="card-body">
          <%= @event.description %>
      </div>

      <div>
          <%= @event.date.to_date %>
          <% if @event.creator && @event.date > DateTime.now %>
              <%= link_to "Invite", invite_path(eventid: @event.id) , class: "btn btn-primary w-25 float-right" %>
          <% end %>
      </div>
  </div>

</div>

<%= render 'attendees'%>

app/views/invitations/new.html.erb
<div class="row m-0">
  <div class="col-md-6 card p-5 m-5">
  <h1>Invite</h1>
  <br>
      <%= form_for @invitation do |f| %>
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, required: true, placeholder: 'example@mail.com' ,class: 'form-control m-2' %>
        <%= f.hidden_field :event_id, value: params[:eventid] %>
        <%= f.hidden_field :event_creator, value: current_user.id %>
        <%= f.submit 'Invite',  class: 'btn btn-primary float-right'%>
      <% end %>
  </div>
</div>

app/views/layouts/_bootstrap.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/_flash_msg.html.erb
<% flash.each do |msg_type, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{msg_type}")%>
<% end %>

app/views/layouts/_footer.html.erb
 
<footer class="footer">
  <small>
    The <a href="https://eventbrite.com/">Private Event</a>
    Created by <a href="http://github.com/macnick">Nick Haras</a> and <a href='https://github.com/addod19'>Daniel Larbi Addo
  </small>
  <nav>
    <ul>
      <li><%= link_to "Events",   events_path, id: "text-red" %></li>
      <li><%= link_to "Users", users_path, id: "text-gold" %></li>
      <li><a href="#top">TOP</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="top">

<nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-dark">
<div class="container">

  <%= link_to "eventbrite", events_path, id: "logo", class: "align-middle navbar-brand text-white"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <% if signed_in? %>
        <li class="nav-item"><%= link_to "Sign out: ", signout_path, method: :delete, class:"nav-link text-danger" %></li>
        <li class="nav-item nav-link text-primary" ><%= link_to "#{current_user.name}", user_path(current_user.id) %></li>
        <li class="nav-item"><%= link_to "Users", users_path, class:"nav-link text-white" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Event actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" class="dark-bg">
            <%= link_to "Show all events", events_path, class: "dropdown-item" %>
            <%= link_to "Create Event", new_event_path, class:"dropdown-item" %>

          </div>
        </li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign in", signin_path, class:"nav-link text-white" %></li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search Events by title" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  </div>
</div>
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= render 'layouts/default' %>
    <%= render 'layouts/bootstrap' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_msg' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages_for_event.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>
    </div>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_user.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_list_events.html.erb
<%if events.blank? %>
    <h3 class="text-center p-5">No <%= type%> events</h3>
<% else %>
    <% events.each do |e| %>
        <div class="card m-4">
            <div class="card-body">
                <h5 class="card-title"><%= e.title%></h5>
                <p class="card-text"><%= e.description%></p>
                <%= link_to "View", event_path(e.id), class: "btn btn-primary float-right"%>
            </div>
            <div class="card-footer text-muted text-right">
                <%= type == 'past' ? time_ago_in_words(e.date) : e.date.to_date %>
                <%if type == 'past'%>
                <span> ago</span>
                <%end%>    
            </div>
        </div>
    <% end %>

<%end%>

app/views/users/_created.html.erb
	<div class="col-xs-4">
		<% if @created.any? %>
			<h3 class="text-center">Created events</h3>
			<ul class="media-list jumbotron">
					<%= render @created %>
			</ul>
		<% else %>
  			<h3>No events created</h3>
		<% end %><br/>
	</div>

app/views/users/_flash.html.erb
<% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages_for_user'%>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.submit "Create User", class: 'btn btn-success form-control mt-1'%>

<% end %>

app/views/users/_list_users.html.erb
<section class="container">

<h3 class="text-center text-success">Listing all users</h3>
    <% if @users.any? %>
            <% @users.each do |user| %>
            <div class="breadcrumb">
            <ul class="event-list">
                <li><h3><%= user.name %></h3></li>
                <li>Location: <%= user.email %></li>
            </ul>
            </div>
            <% end %>
    <% else %>
        <h4 class="breadcrumb">There are no users yet.</h4>   
    <% end %>

    </section>

app/views/users/create.html.erb
<h1>this is create template</h1>

app/views/users/index.html.erb
<h3 class="text-center">Welcome to Eventbrite!</h3>

<div class="row bg">
  <div class="center text-white bg-dark">
    <p>
      Hi, <% if signed_in? %>
          <%= current_user.name %>
        <% else %>
        <h6>Friends</h6>
        <% end %>
    </p>
    <p>
        You can : 
          <% if signed_in? %>
            <%= link_to "Sign out", signout_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', signin_path %>
          <% end %>
          or <%= link_to 'Sign up', new_user_path %>
    </p>
  </div>
</div>
<hr>
<%= render 'list_users'%>

app/views/users/new.html.erb
<h3 class="text-center mt-1">Sign Up</h3>
<div class="row mt-1">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <%= render 'form'%>
    </div>
    <div class="col-md-3"></div>
</div>

app/views/users/show.html.erb
<h1 class="text-center text-white bg-info rounded mt-1">This is <%= "#{@user.name}" %> personal page</h1>


<section class="container m-5">
<h2 class="m-4">Events</h2>

        <ul class="nav nav-pills nav-fill m-5" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-upcoming-tab" data-toggle="pill" href="#pills-upcoming" role="tab" aria-controls="pills-upcoming" aria-selected="true">Upcoming events</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-past-tab" data-toggle="pill" href="#pills-past" role="tab" aria-controls="pills-past" aria-selected="false">Past events</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-created-tab" data-toggle="pill" href="#pills-created" role="tab" aria-controls="pills-created" aria-selected="false">Created events</a>
        </li>
        </ul>


    <div class="container">
        <div class="tab-content" id="pills-content-tab">
            <div class="tab-pane fade show active" id="pills-upcoming" role="tabpanel" aria-labelledby="pills-upcoming-tab">
                <%= render 'shared/list_events', {events: @user.upcoming_events, type: 'upcoming'} %>
        </div>
        <div class="tab-pane fade" id="pills-past" role="tabpanel" aria-labelledby="pills-past-tab">
                <%= render 'shared/list_events', {events: @user.past_events, type: 'past'} %>         
        </div>
        <div class="tab-pane fade" id="pills-created" role="tabpanel" aria-labelledby="pills-created-tab">
                <%= render 'shared/list_events', {events: @user.events, type: 'created'} %>         
        </div>
        </div>
    </div>
</section>